transaction = "  nguyEN vAn a | PYTHON-01 | 15000000 | paid  ".strip()
name=transaction.split('|')[0].title()
khoa_hoc=transaction.split('|')[1].upper()
money=int(transaction.split("|")[2])
status=transaction.split("|")[3].upper()
print(f'Học viên:{name}')
print(f'Khoá học:{khoa_hoc}')
print(f'Số tiền :{money:,}')
print(f'Trạng thái:{status}')   
